server:
  port: 9999


spring:
  datasource:
    url: jdbc:mysql://119.91.192.36:3308/try?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: info
    sql: debug
    web: debug
    com.lowic.data.analysis: DEBUG
    com.baomidou.mybatisplus: DEBUG


