server:
  port: 9999


spring:
  datasource:
    url: jdbc:mysql://119.91.192.36:3308/try?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


